apiVersion: v1
kind: Pod 
metadata: 
  name: load-balancer-pod 
  labels:
    project: load-balancer-pod
    app: load-balancer
    env: Dev
spec:
  containers:
  - name: load-balancer-container
    image: nginx 
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service 
metadata: 
  name: load-balancer-service
spec:
  type: LoadBalancer
  selector:
    project: load-balancer-pod
    app: load-balancer
    env: Dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 35000



