apiVersion: v1 
kind: Pod
metadata: 
  name: resource-demo
  labels:
    name: "resources_pod"
    usage: "limiting_the_cpu_usage"
  annotations:
    resources: "the resources we have used here is to restrict the cpu"
spec:
  containers:
  - name: resource
    image: nginx
    ports: 
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "125m"
        memory: "124Mi"
