apiVersion: v1 
kind: Pod 
metadata: 
  name: secret-pod
  labels:
    env: dev
    app: nginx
    service: network
spec:
  containers:
  - name: secret-pod
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: roboshop-secret

---

apiVersion: v1
kind: Service 
metadata:
  name: service_nginx
spec:
  selector:
    env: dev
    app: nginx
    service: network
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

