apiVersion: v1 
kind: Pod 
metadata: 
  name: secret-pod
  labels:
    env: dev
    app: nginx
    service: network
spec:
  containers:
  - name: secret-pod
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: roboshop-secret

---


