apiVersion: v1
kind: Pod 
metadata:
  name: service-pod
spec:
  containers:
  - name: service-pod
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service 
metadata:
  name: service-nginx
spec:
  selector:
    env: dev
    app: nginx
    service: network
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
