apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  selector:
    name: service-labels        # must exist on your Pods
    connection: nodeport        # just a label; optional if your Pods have it
  ports:
    - protocol: TCP
      port: 80                  # service port
      targetPort: 80            # container port
