apiVersion: v1
kind: Pod 
metadata:
  name: nodeport-pod
  labels:
    env: Dev
    app: zomato
    project: food
spec:
  containers:
  - name: nodeport-podcontainer
    image: nginx
    ports:
    - containerPort: 80


---

apiVersion: v1
kind: Service 
metadata: 
  name: nodeport-service
spec:
  type: NodePort
  selector:
    env: Dev
    app: zomato
    project: food
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
